- name: Ensure MySQL is installed
  ansible.builtin.apt:
    name: mysql-server
    state: present
  become: yes

- name: Ensure MySQL is running
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Create database
  mysql_db:
    name: mydb
    state: present

- name: Create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: 'mydb.*:ALL'
    host: "%"
    state: present